services:
  next:
   image: node:20-alpine
   container_name: next_frontend
   working_dir: /app
   ports:
    - "3000:3000"
   volumes:
      - ./frontend/url-shortener:/app
      - /app/node_modules   # waÅ¼ne na Windows/Mac
   command: >
      sh -c "npm install && npm run dev"
  php:
    image: php:8.4-cli-alpine
    build: 
      context: ./backend/url-shortener
    container_name: symfony_php
    ports:
      - "8000:8000" # Symfony server
    volumes:
      - ./backend/url-shortener:/srv/app
    depends_on:
      database:
        condition: service_healthy
    command: >
      sh -c "php -S 0.0.0.0:8000 -t public"
  ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-SU1DB2PW}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_ROOT_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: md5
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-d",
          "${POSTGRES_DB:-app}",
          "-U",
          "${POSTGRES_USER:-admin}",
        ]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

  app_test:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: app_test
      # You should definitely change the password in production
      POSTGRES_PASSWORD: SU1DB2PW
      POSTGRES_USER: admin
      POSTGRES_HOST_AUTH_METHOD: md5
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  message-consumer:
    image: php:8.4-cli-alpine
    build: 
      context: ./backend/url-shortener
    container_name: message_consumer
    volumes:
      - ./backend/url-shortener:/srv/app
    depends_on:
      database:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    command: >
      php bin/console messenger:consume async --time-limit=3600 --memory-limit=128M
    restart: unless-stopped


volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
